# Screen settings
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Cell settings
CELL_SIZE = 20

# Map settings
MAP_WIDTH = WINDOW_WIDTH // CELL_SIZE
MAP_HEIGHT = WINDOW_HEIGHT // CELL_SIZE

# Snake settings
SNAKE_INIT_POS = (MAP_WIDTH // 2, MAP_HEIGHT // 2)

